### ISSUE TITLE
Update to open-korean-text-2.0.1.

### ISSUE THREAD

**Issue by hohyon-ryu** [openkoreantext/open-korean-text-api#12]

**Comment by MechanicKim** [comment]
I tried to update this API but I can't! 😢
<img width="543" alt="2017-05-20 11 47 28" src="https://cloud.githubusercontent.com/assets/12149783/26272408/38d1899e-3d52-11e7-9d60-64ec210d4f79.png">

I confirmed that open-korean-text-2.0.1 includes the classes and also confirmed that the library has a problem.

<img width="664" alt="2017-05-20 11 50 30" src="https://cloud.githubusercontent.com/assets/12149783/26272420/931e0b2a-3d52-11e7-8ec5-4959b6c60c00.png">

Please confirm it. @nlpenguin 
Thanks!

**Comment by MechanicKim** [comment]
Updated to 2.0.2!
Thanks @nlpenguin 😁

**Comment by hohyon-ryu** [comment]
Please let me know after you deploy!
